<?php

use gamboamartin\errores\errores;

class partida_factura extends modelos {

    public function alta_bd($registro, $tabla): array
    {


        $r_alta_bd = parent::alta_bd($registro, $tabla); // TODO: Change the autogenerated stub
        if(errores::$error){
            return $this->error->error('Error al dar5 de alta partida', $r_alta_bd);
        }

        if(isset($registro['factura_id'])){
            $factura_id = $registro['factura_id'];
            $filtros['partida_factura.factura_id'] = $factura_id;
            $r_partida = (new partida_factura($this->link))->filtro_and('partida_factura', $filtros);
            if(errores::$error){
                return $this->error->error('Error al obtener partidas', $r_partida);
            }
            $partidas = $r_partida['registros'];
            foreach($partidas as $partida){
                $partida_factura_id = $partida['partida_factura_id'];
                if(isset($partida['insumo_id'])){
                    $insumo_id = $partida['insumo_id'];
                    $insumo = (new insumo($this->link))->data_insumo(insumo_id: $insumo_id);
                    if(errores::$error){
                        return $this->error->error('Error al obtener insumo', $insumo);
                    }
                    if(isset($insumo['insumo_obj_imp']) && $insumo['insumo_obj_imp']!==''){
                        $obj_imp = trim($insumo['insumo_obj_imp']);
                        $obj_imp_ant = trim($partida['partida_factura_obj_imp']);

                        if($obj_imp!==$obj_imp_ant){
                            $part_fact_upd['obj_imp'] = $obj_imp;
                            $r_part_fact = $this->modifica_bd(registro: $part_fact_upd, tabla: 'partida_factura', id:$partida_factura_id);
                            if(errores::$error){
                                return $this->error->error('Error al actualizar partida insumo', $r_part_fact);
                            }
                        }

                    }
                }
            }
        }

        return $r_alta_bd;
    }

}
